spring.application.name=aircraft-management-api
spring.datasource.url=jdbc:postgresql://localhost:5432/aircraft_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mySuperSecretKeyThatIsAtLeast32CharactersLongForHS256
jwt.expiration=86400000

spring.profiles.active=s3

# Storage
storage.type=s3
storage.local.path=./uploads

aws.s3.bucket=aircraft-images-felipe
aws.region=sa-east-1

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#aws.accessKeyId=${AWS_ACCESS_KEY_ID:}
#aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY:}